<?php

/*
echo "<p class=\"copyright\">\n";
echo "<a href=\"http://jigsaw.w3.org/css-validator/validator?uri=";
echo "http://$HostName$ThisScript\">";
echo "<img align=\"top\" style=\"border:0;width:88px;height:31px\"";
echo " src=\"http://jigsaw.w3.org/css-validator/images/vcss\""; 
echo " alt=\"Valid CSS!\">";
echo "</a>\n";

echo "<a href=\"http://validator.w3.org/check?uri=";
echo "http://$HostName$ThisScript\">";
echo "<img align=\"top\" style=\"border:0;width:88px;height:31px\"";
echo " src=\"http://www.w3.org/Icons/valid-html401\""; 
echo " alt=\"Valid HTML 4.01!\">";
echo "</a>\n";
*/

echo "\n\n<div class=\"footer\">";
echo "$copy";
echo "<br />" . __('Generated by') . "\n   <em>";
echo "<a href=\"" . $app["url"] . "\">";
echo $app["name"];
echo "</a>";
echo " ver. " . $app["version"];
echo "</em>\n";
echo "</div>\n";
?>

          <a href="http://www.mozilla.org/products/firefox/" title="Get Firefox - Web Browsing Redefined">
            <img src="http://www.mozilla.org/products/firefox/buttons/firefox_pixel.png" width="94" height="15" alt="Get Firefox" />
          </a> 

<script type="text/javascript">
	var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
	document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
	var pageTracker = _gat._getTracker("UA-xxxxxx-x");
	pageTracker._initData();
	pageTracker._trackPageview();
</script>